// apps/shared-ui-library/angular/src/lib/spinner/spinner.component.ts
import { Component, input } from '@angular/core';

const SIZE_CLASSES: Record<'sm' | 'md' | 'lg', string> = {
  sm: 'h-3.5 w-3.5 border-2',
  md: 'h-5 w-5 border-2',
  lg: 'h-8 w-8 border-[3px]'
};

@Component({
  selector: 'ui-spinner',
  standalone: true,
  template: `
    <span
      role="status"
      [attr.aria-label]="label()"
      [class]="'inline-block animate-spin rounded-full border-current border-t-transparent ' + sizeClass()"
    ></span>
  `
})
export class SpinnerComponent {
  readonly size = input<'sm' | 'md' | 'lg'>('md');
  readonly label = input('Loading');

  protected sizeClass(): string {
    return SIZE_CLASSES[this.size()];
  }
}

// apps/shared-ui-library/react/src/components/Spinner.tsx
export interface SpinnerProps {
  size?: 'sm' | 'md' | 'lg';
  className?: string;
  label?: string;
}

const SIZE_PX: Record<NonNullable<SpinnerProps['size']>, string> = {
  sm: 'h-3.5 w-3.5 border-2',
  md: 'h-5 w-5 border-2',
  lg: 'h-8 w-8 border-[3px]'
};

/** Minimal, dependency-free spinner — an SVG import would be overkill for a single ring. */
export function Spinner({ size = 'md', className = '', label = 'Loading' }: SpinnerProps) {
  return (
    <span
      role="status"
      aria-label={label}
      className={`inline-block animate-spin rounded-full border-current border-t-transparent ${SIZE_PX[size]} ${className}`}
    />
  );
}
