// apps/shared-ui-library/angular/src/lib/stat-card/stat-card.component.ts
import { Component, input } from '@angular/core';
import { CardComponent } from '../card/card.component';

export type StatDeltaDirection = 'up' | 'down' | 'flat';

const DELTA_COLOR: Record<StatDeltaDirection, string> = {
  up: 'text-success',
  down: 'text-danger',
  flat: 'text-white/50'
};

const DELTA_ARROW: Record<StatDeltaDirection, string> = { up: '▲', down: '▼', flat: '•' };

/** KPI tile used on dashboards and overview pages. */
@Component({
  selector: 'ui-stat-card',
  standalone: true,
  imports: [CardComponent],
  template: `
    <ui-card [tone]="tone()" class="flex flex-col gap-2">
      <div class="flex items-center justify-between">
        <span [class]="'text-xs uppercase tracking-wide ' + (tone() === 'dark' ? 'text-white/50' : 'text-ink-700/60')">
          {{ label() }}
        </span>
      </div>
      <span [class]="'font-display text-3xl ' + (tone() === 'dark' ? 'text-white' : 'text-ink-950')">{{ value() }}</span>
      @if (deltaValue()) {
        <span [class]="'text-xs font-medium ' + deltaColor()">{{ deltaArrow() }} {{ deltaValue() }}</span>
      }
    </ui-card>
  `
})
export class StatCardComponent {
  readonly label = input.required<string>();
  readonly value = input.required<string | number>();
  readonly tone = input<'dark' | 'light'>('dark');
  readonly deltaValue = input<string>('');
  readonly deltaDirection = input<StatDeltaDirection>('flat');

  protected deltaColor(): string {
    return DELTA_COLOR[this.deltaDirection()];
  }

  protected deltaArrow(): string {
    return DELTA_ARROW[this.deltaDirection()];
  }
}

// apps/shared-ui-library/react/src/components/StatCard.tsx
import { ReactNode } from 'react';
import { Card } from './Card';

export interface StatCardProps {
  label: string;
  value: ReactNode;
  delta?: { value: string; direction: 'up' | 'down' | 'flat' };
  icon?: ReactNode;
  tone?: 'dark' | 'light';
}

const DELTA_COLOR = {
  up: 'text-success',
  down: 'text-danger',
  flat: 'text-white/50'
};

/** KPI tile used on both the admin dashboard and the tenant overview. */
export function StatCard({ label, value, delta, icon, tone = 'dark' }: StatCardProps) {
  return (
    <Card tone={tone} className="flex flex-col gap-2">
      <div className="flex items-center justify-between">
        <span className={`text-xs uppercase tracking-wide ${tone === 'dark' ? 'text-white/50' : 'text-ink-700/60'}`}>
          {label}
        </span>
        {icon && <span className={tone === 'dark' ? 'text-saffron-500' : 'text-saffron-600'}>{icon}</span>}
      </div>
      <span className={`font-display text-3xl ${tone === 'dark' ? 'text-white' : 'text-ink-950'}`}>{value}</span>
      {delta && (
        <span className={`text-xs font-medium ${DELTA_COLOR[delta.direction]}`}>
          {delta.direction === 'up' ? '▲' : delta.direction === 'down' ? '▼' : '•'} {delta.value}
        </span>
      )}
    </Card>
  );
}
