// apps/react-admin/bus-ticketing-admin/src/modules/auth/pages/LoginPage.tsx
import { FormEvent, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../AuthContext';
import { Button, Card, Input } from '@shared-ui/react';

export default function LoginPage() {
  const { login, submitting, error } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [email, setEmail] = useState('admin@transport.local');
  const [password, setPassword] = useState('password123');

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    const ok = await login({ email, password });
    if (ok) {
      const redirectTo = (location.state as { redirectTo?: string } | null)?.redirectTo ?? '/dashboard';
      navigate(redirectTo, { replace: true });
    }
  }

  return (
    <main className="min-h-screen bg-ink-950 flex items-center justify-center px-6 py-16">
      <div className="w-full max-w-sm">
        <p className="text-saffron-500 text-sm tracking-[0.2em] uppercase mb-2 text-center">Bus Ticketing</p>
        <h1 className="font-display text-3xl text-white text-center mb-8">Admin console</h1>

        <Card>
          <form onSubmit={onSubmit} className="flex flex-col gap-4">
            <Input
              label="Email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@transport.local"
            />
            <Input
              label="Password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="••••••••"
            />

            {error && <p className="text-danger text-sm bg-danger-bg rounded-md px-3 py-2">{error}</p>}

            <Button type="submit" loading={submitting} className="w-full mt-1">
              Sign in
            </Button>
          </form>
        </Card>

        <p className="text-white/30 text-xs text-center mt-4">Demo mode — any email/password combination signs you in.</p>
      </div>
    </main>
  );
}

// apps/angular-client/bus-ticketing-customer-web/src/app/features/auth/pages/login-page/login-page.component.ts
import { Component, inject } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthStore } from '../../../../core/auth/auth.store';
import { ButtonComponent } from '@shared-ui/button/button.component';
import { InputComponent } from '@shared-ui/input/input.component';
import { CardComponent } from '@shared-ui/card/card.component';

@Component({
  selector: 'app-login-page',
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink, ButtonComponent, InputComponent, CardComponent],
  template: `
    <main class="min-h-screen bg-ink-950 flex items-center justify-center px-6 py-16">
      <div class="w-full max-w-sm">
        <p class="text-saffron-500 text-sm tracking-[0.2em] uppercase mb-2 text-center">Bus Ticketing</p>
        <h1 class="font-display text-3xl text-white text-center mb-8">Welcome back</h1>

        <ui-card>
          <form [formGroup]="form" (ngSubmit)="onSubmit()" class="flex flex-col gap-4">
            <ui-input formControlName="email" type="email" label="Email" placeholder="you@example.com" />
            <ui-input formControlName="password" type="password" label="Password" placeholder="••••••••" />

            @if (authStore.error()) {
              <p class="text-danger text-sm bg-danger-bg rounded-md px-3 py-2">{{ authStore.error() }}</p>
            }

            <ui-button type="submit" [loading]="authStore.submitting()" class="w-full mt-1">
              Sign in
            </ui-button>
          </form>
        </ui-card>

        <p class="text-white/50 text-sm text-center mt-6">
          New here?
          <a routerLink="/auth/register" class="text-saffron-500 underline">Create an account</a>
        </p>

        <p class="text-white/30 text-xs text-center mt-3">
          Demo mode — any email/password combination signs you in.
        </p>
      </div>
    </main>
  `
})
export class LoginPageComponent {
  private readonly fb = inject(FormBuilder);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);
  protected readonly authStore = inject(AuthStore);

  protected readonly form = this.fb.nonNullable.group({
    email: ['demo@example.com', [Validators.required, Validators.email]],
    password: ['password123', [Validators.required, Validators.minLength(6)]]
  });

  protected async onSubmit(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    const ok = await this.authStore.login(this.form.getRawValue());
    if (ok) {
      const redirectTo = this.route.snapshot.queryParamMap.get('redirectTo') ?? '/profile/bookings';
      this.router.navigateByUrl(redirectTo);
    }
  }
}
